# Generated by Django 4.2.5 on 2024-04-27 01:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_customuser_is_staff_alter_customuser_is_superuser'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='usermame',
            new_name='username',
        ),
    ]
